import type { Subcontractor } from "../types";

export const INITIAL_SUBCONTRACTORS: Subcontractor[] = [
  {
    id: "sub-1",
    name: "Apex Concrete Works",
    trades: ["03 30 00"],
    rating: 4.8,
    projects: 24,
    responseSpeed: "Fast",
  },
  {
    id: "sub-2",
    name: "Solid Foundations Ltd.",
    trades: ["03 30 00", "03 15 00"],
    rating: 4.2,
    projects: 12,
    responseSpeed: "Average",
  },
  {
    id: "sub-3",
    name: "City Pours",
    trades: ["03 30 00"],
    rating: 3.9,
    projects: 8,
    responseSpeed: "Slow",
  },
  {
    id: "sub-4",
    name: "Prime Painters",
    trades: ["09 90 00"],
    rating: 5.0,
    projects: 41,
    responseSpeed: "Fast",
  },
  {
    id: "sub-5",
    name: "Elite Drywall & Framing",
    trades: ["09 22 00", "06 10 00"],
    rating: 4.5,
    projects: 19,
    responseSpeed: "Fast",
  },
  {
    id: "sub-6",
    name: "ProCoat Finishes",
    trades: ["09 90 00", "09 22 00"],
    rating: 4.1,
    projects: 15,
    responseSpeed: "Average",
  },
  {
    id: "sub-7",
    name: "Volt Masters",
    trades: ["26 05 00"],
    rating: 4.9,
    projects: 33,
    responseSpeed: "Fast",
  },
  {
    id: "sub-8",
    name: "Cornerstone Concrete Group",
    trades: ["03 30 00", "03 20 00"],
    rating: 4.6,
    projects: 21,
    responseSpeed: "Fast",
  },
  {
    id: "sub-9",
    name: "Precision Flatwork Co.",
    trades: ["03 30 00"],
    rating: 4.4,
    projects: 17,
    responseSpeed: "Average",
  },
  {
    id: "sub-10",
    name: "Blue Ridge Concrete",
    trades: ["03 30 00"],
    rating: 4.3,
    projects: 14,
    responseSpeed: "Fast",
  },
  {
    id: "sub-11",
    name: "Metro Slab Solutions",
    trades: ["03 30 00"],
    rating: 4.0,
    projects: 11,
    responseSpeed: "Average",
  },
  {
    id: "sub-12",
    name: "Ironclad Form & Pour",
    trades: ["03 30 00", "03 15 00", "03 20 00"],
    rating: 4.7,
    projects: 27,
    responseSpeed: "Fast",
  },
  {
    id: "sub-13",
    name: "Civic Concrete Partners",
    trades: ["03 30 00"],
    rating: 3.8,
    projects: 9,
    responseSpeed: "Slow",
  },
  {
    id: "sub-14",
    name: "Rapid Pour Contractors",
    trades: ["03 30 00"],
    rating: 4.1,
    projects: 13,
    responseSpeed: "Fast",
  },
  {
    id: "sub-15",
    name: "Atlas Reinforced Concrete",
    trades: ["03 30 00"],
    rating: 4.5,
    projects: 20,
    responseSpeed: "Average",
  },
  {
    id: "sub-16",
    name: "Stonebridge Structural Concrete",
    trades: ["03 30 00"],
    rating: 4.2,
    projects: 16,
    responseSpeed: "Fast",
  },
  {
    id: "sub-17",
    name: "Foundry Concrete Services",
    trades: ["03 30 00"],
    rating: 3.9,
    projects: 10,
    responseSpeed: "Average",
  },
];
